language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - 'node'

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - npm install -g typescript@2.0.2

script:
  - "npm run test"
  - "npm run test:travis"

after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 remap-istanbul@0.6.4 && ./node_modules/.bin/remap-istanbul -i ./coverage/coverage.json -t lcovonly | coveralls"

sudo: required
